// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {power} from '../models';

export function AnalyzeETLFile(arg1:string):Promise<backend.ETLAnalysisResult>;

export function ApplyEPP(arg1:number,arg2:number):Promise<string>;

export function ApplyHetero(arg1:number,arg2:number):Promise<string>;

export function ApplyMaxFrequency(arg1:number,arg2:number):Promise<string>;

export function ApplySoftParkLatency(arg1:number,arg2:number):Promise<string>;

export function AskAIAgent(arg1:string):Promise<string>;

export function AskNVIDIACloud(arg1:string):Promise<string>;

export function CheckAllToolkitInstalled():Promise<Array<backend.ToolkitInstallStatus>>;

export function CheckDYTCCapabilities():Promise<Record<string, boolean>>;

export function CheckNVIDIAStatus():Promise<backend.NVIDIAStatus>;

export function CheckToolkitInstalled(arg1:string):Promise<backend.ToolkitInstallStatus>;

export function EnableDynamicLog():Promise<backend.DynamicLogResult>;

export function EnumerateAllNamespaces():Promise<string>;

export function EnumerateGPUProcesses():Promise<Array<backend.GPUProcess>>;

export function EnumerateGPUs():Promise<Array<backend.GPUInfo>>;

export function GenerateWMIEventCode(arg1:string):Promise<string>;

export function GenerateWMIMethodCode(arg1:string):Promise<string>;

export function GenerateWMIQueryCode(arg1:string):Promise<string>;

export function GetAIAgentSystemInfo():Promise<backend.AIAgentSystemInfo>;

export function GetCachedGPUStatus():Promise<number>;

export function GetCachedSystemPower():Promise<backend.SystemPowerInfo>;

export function GetClassDetails(arg1:string,arg2:string):Promise<string>;

export function GetClassesInNamespace(arg1:string):Promise<string>;

export function GetDYTCInfo():Promise<backend.DYTCInfo>;

export function GetDispatcherInfo():Promise<backend.DispatcherInfo>;

export function GetDynamicLogStatus():Promise<boolean>;

export function GetEPOTStatus():Promise<backend.EPOTStatus>;

export function GetETLCaptureStatus():Promise<backend.ETLCaptureState>;

export function GetETLProfiles():Promise<Array<backend.ETLProfile>>;

export function GetETLTraceList():Promise<Array<backend.ETLTraceInfo>>;

export function GetEventClasses():Promise<string>;

export function GetGPUAutoGear():Promise<backend.GPUAutoGear>;

export function GetGPUPrefStatus():Promise<backend.GPUPrefStatus>;

export function GetGPUPrefStatusFromCache():Promise<backend.GPUPrefStatus>;

export function GetIGPUMode():Promise<backend.IGPUStatus>;

export function GetInstalledToolkitTools():Promise<Array<string>>;

export function GetIntelDriverDownloadURL():Promise<string>;

export function GetIntelGPUFrequency():Promise<backend.IntelGPUFrequency>;

export function GetIntelGPUUtilization():Promise<number>;

export function GetLogFiles():Promise<Array<backend.LogFileInfo>>;

export function GetLogSummary():Promise<Record<string, any>>;

export function GetMLLogStatus():Promise<backend.MLLogStatus>;

export function GetModeCheckInfo():Promise<backend.ModeCheckInfo>;

export function GetNPOSchedulerSettings():Promise<backend.NPOSchedulerSettings>;

export function GetNPOSchedulerState():Promise<backend.NPOSchedulerState>;

export function GetNPUDeviceInfo():Promise<backend.NPUDeviceInfo>;

export function GetNPUDeviceInfoWrapper():Promise<backend.NPUDeviceInfo|string>;

export function GetNPUDeviceMetrics(arg1:number):Promise<backend.NPUDeviceMetrics>;

export function GetNPUDeviceOverview(arg1:number):Promise<backend.NPUDeviceOverview>;

export function GetNPUDeviceProperties(arg1:number):Promise<backend.NPUDeviceProperties>;

export function GetNPUFullReport():Promise<backend.NPUFullReport>;

export function GetNPUPowerStatus(arg1:number):Promise<backend.NPUPowerStatus>;

export function GetNPUREport():Promise<string>;

export function GetNPUSDKInfo():Promise<backend.NPUSDKInfo>;

export function GetNVIDIAModelList():Promise<string>;

export function GetPPMDrivers():Promise<Array<backend.PPMDriverInfo>>;

export function GetPPMPlatformInfo():Promise<backend.PPMPlatformInfo>;

export function GetPPMSettings():Promise<backend.PPMSettings>;

export function GetPinnedDYTCMode():Promise<string>;

export function GetPowerStatus():Promise<Record<string, boolean>>;

export function GetSSDInfo():Promise<Array<backend.SSDInfo>>;

export function GetServiceStatus():Promise<string>;

export function GetSystemInfo():Promise<backend.SystemInfo>;

export function GetSystemPowerInfo():Promise<backend.SystemPowerInfo>;

export function GetToolkitInstallDir():Promise<string>;

export function GetToolkitProgress(arg1:string):Promise<backend.ToolkitInstallProgress>;

export function GetToolkitTools():Promise<Array<backend.ToolkitTool>>;

export function GetWMIExplorer():Promise<string>;

export function InitPowerMonitor():Promise<power.InitResult>;

export function InstallDTTUI():Promise<string>;

export function InstallToolkitTool(arg1:string):Promise<backend.ToolkitInstallProgress>;

export function InvokeWMI(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function IsElevated():Promise<boolean>;

export function IsNVIDIAEnabled():Promise<boolean>;

export function IsToolkitBusy(arg1:string):Promise<boolean>;

export function LoadNVIDIAConfig():Promise<backend.NVIDIAAPIConfig>;

export function NPUGetDVFSMode(arg1:number):Promise<string>;

export function NPUSetDVFSMode(arg1:number,arg2:string):Promise<string>;

export function OpenETLFileDialog():Promise<string>;

export function OpenETLInWPA(arg1:string):Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenTestMode():Promise<Record<string, any>>;

export function OpenToolkitFolder():Promise<string>;

export function PinDYTCMode(arg1:string):Promise<string>;

export function ReadLogTail(arg1:number):Promise<string>;

export function ReadPower():Promise<power.PowerReading>;

export function ResetNPUDefaults(arg1:number):Promise<backend.NPUPowerAction>;

export function RestartService():Promise<string>;

export function RestoreDefaults():Promise<string>;

export function RunToolkitTool(arg1:string):Promise<string>;

export function SaveNVIDIAConfig(arg1:backend.NVIDIAAPIConfig):Promise<void>;

export function SetDYTCMode(arg1:string):Promise<string>;

export function SetGEEKMode(arg1:boolean):Promise<string>;

export function SetGPUAutoGear(arg1:number):Promise<backend.SetResult>;

export function SetIGPUMode(arg1:number):Promise<backend.SetResult>;

export function SetIntelGPUFrequencyRange(arg1:number,arg2:number):Promise<backend.IntelGPUFreqTestResult>;

export function SetNPUClockLock(arg1:number,arg2:number,arg3:number):Promise<backend.NPUPowerAction>;

export function SetNPUMode(arg1:number,arg2:string):Promise<backend.NPUPowerAction>;

export function SetNPUPowerLimit(arg1:number,arg2:number,arg3:number):Promise<backend.NPUPowerAction>;

export function SetODV(arg1:number,arg2:number):Promise<string>;

export function SetPowerSettingRaw(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SetSSDMode(arg1:number,arg2:number):Promise<backend.SSDModeResult>;

export function ShutdownPowerMonitor():Promise<void>;

export function StartETLCapture(arg1:string,arg2:number):Promise<backend.ETLCaptureState>;

export function StartGPUStatusWatcher():Promise<void>;

export function StartMLScenarioCapture():Promise<backend.MLLogStatus>;

export function StartNPUScheduler(arg1:number,arg2:backend.NPOSchedulerSettings):Promise<void>;

export function StartService():Promise<string>;

export function StopETLCapture():Promise<backend.ETLTraceInfo>;

export function StopGPUStatusWatcher():Promise<void>;

export function StopMLScenarioCapture():Promise<backend.MLLogStatus>;

export function StopNPUScheduler():Promise<void>;

export function StopService():Promise<string>;

export function TestIntelGPUFrequency(arg1:string):Promise<backend.IntelGPUFreqTestResult>;

export function TestNVIDIAConnection(arg1:string,arg2:string):Promise<string>;

export function UninstallDTT():Promise<string>;

export function UninstallDTTUI():Promise<string>;

export function UninstallDispatcher():Promise<backend.UninstallResult>;

export function UninstallToolkitTool(arg1:string):Promise<string>;

export function UnpinDYTCMode():Promise<void>;

export function UpdateCachedSystemPower():Promise<backend.SystemPowerInfo>;
